name: Android CI Build

on:
  workflow_dispatch: # 允许你手动点击

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # 降回最稳定的 v3 版本，防止官方 v4 抽风

    - name: Set up JDK 17
      uses: actions/setup-java@v3  # 同样用最稳的 v3
      with:
        java-version: '17'
        distribution: 'zulu'       # 换成 zulu 镜像源，国内和国际连线最稳的节点
        cache: gradle

    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew

    - name: Build APK with Gradle
      run: ./gradlew assembleDebug

    - name: Upload Generated APK artifact
      uses: actions/upload-artifact@v3  # 保持版本一致性
      with:
        name: SillyOS-Client-Debug-APK
        path: app/build/outputs/apk/debug/*.apk

